language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  
env:
  - DJANGO_VERSION=3.2.7
  
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors
  
script: python manage.py test
